const mongoose = require("mongoose");

const defaultKalashYatraData = {
  hero: {
    liveBadgeText: "Sacred Pledge Campaign • National Mega Event",
    headingMain: "Kalash Yatra",
    headingHighlight: "Sacred Confluence of Unity, Culture & Self-Respect",
    subheading:
      "Nurtured by sacred river waters, this mega campaign unites society, inspires cultural consciousness, and sounds the historic call for a self-reliant nation.",
    highlights: [
      "Sacred reverence of Ganga, Saryu, Narmada, and Gandak waters",
      "Unmatched leadership and participation of women",
      "Awakening of social harmony and civic consciousness",
    ],
    primaryBtnText: "Watch Sacred Videos",
    primaryBtnLink: "#videoGallery",
    secondaryBtnText: "Join the Pledge",
    secondaryBtnLink: "#pillarsSection",
    stats: [
      { number: "150+", label: "Districts Reached", sub: "Sacred Pledge Journey" },
      { number: "50,000+", label: "Auspicious Kalash Worship", sub: "Vedic Rituals" },
      { number: "10,000+", label: "Women Leadership", sub: "Leading the Forefront" },
      { number: "28+", label: "States Awakened", sub: "National Campaign" },
    ],
    featuredVideo: {
      title: "Grand Historic Kalash Yatra Inauguration — Mega Event",
      duration: "12:45 Min",
      videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      posterImage: "/images/kalash-yatra-hero.jpg",
      badge: "★ Featured Video",
    },
  },

  milestonesSection: {
    kicker: "★ Special Compilation • Nishad Sankalp Campaign",
    title: "Kalash Yatra — ",
    titleHighlight: "A Sacred Journey of Unity and Commitment",
    subtitle:
      "From Gopalganj to Kashi, Ayodhya, Bhopal, and Ranchi — key milestones across 150+ districts awakening harmony and dignity with sacred river waters.",
    items: [
      {
        stateKey: "bihar",
        stateName: "Bihar",
        district: "Gopalganj",
        title: "Historic Gopalganj Kalash Yatra",
        image: "/images/kalash-yatra-featured.jpg",
        description:
          "Thousands of women carried auspicious kalash on their heads, conveying a divine message of harmony and community awakening.",
        tag: "🚩 Milestone 1",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        order: 1,
      },
      {
        stateKey: "uttar-pradesh",
        stateName: "Uttar Pradesh",
        district: "Varanasi Ghat",
        title: "Ganga Worship on Sacred Ghats of Kashi",
        image: "/images/ghat-kalash-procession.jpg",
        description:
          "Reverence of holy waters with conch sounds and Vedic chants at Dashashwamedh and Assi Ghats.",
        tag: "🌊 Sacred Ganga Reverence",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        order: 2,
      },
      {
        stateKey: "uttar-pradesh",
        stateName: "Uttar Pradesh",
        district: "Ayodhya - Prayagraj",
        title: "Ayodhya-Prayagraj Confluence",
        image: "/images/sacred-kalash-ritual.jpg",
        description:
          "Traditional Vedic installation with mango leaves and sacred coconuts, showcasing magnificent community unity.",
        tag: "🪔 Vedic Ceremony",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        order: 3,
      },
      {
        stateKey: "madhya-pradesh",
        stateName: "Madhya Pradesh",
        district: "Bhopal",
        title: "Bhopal Mega Convention & Public Gathering",
        image: "/images/kalash-yatra-hero.jpg",
        description:
          "Historic gathering of thousands of devotees from Narmadanchal rising for collective self-respect.",
        tag: "🏛️ Mega Convention",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        order: 4,
      },
      {
        stateKey: "jharkhand",
        stateName: "Jharkhand",
        district: "Ranchi",
        title: "Ranchi Sacred Kalash Procession",
        image: "/images/ranchi-kalash-procession.jpg",
        description:
          "Auspicious pledge ceremony along the banks of the Subarnarekha River with extensive tribal and coastal participation.",
        tag: "🌿 Dignity Journey",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        order: 5,
      },
    ],
  },

  videos: [
    {
      title: "गोपालगंज में भव्य कलश यात्रा — 5000+ माताओं-बहनों की ऐतिहासिक सहभागिता",
      videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      thumbnail: "/images/kalash-yatra-hero.jpg",
      personOrPlace: "मातृशक्ति सम्मेलन, गोपालगंज मुख्य चौक",
      category: "yatra",
      state: "bihar",
      district: "गोपालगंज",
      duration: "14:20 Min",
      viewsCount: "18.5K",
      date: "14 जनवरी 2024",
      description:
        "गोपालगंज जिले में आयोजित इस पावन कलश यात्रा में समाज के हर वर्ग ने उत्साहपूर्वक भाग लिया। वैदिक मंत्रोच्चार के बीच गंगा-गंडक जल का अर्चन किया गया।",
      tag: "कलश यात्रा",
      order: 1,
    },
    {
      title: "वाराणसी दशाश्वमेध घाट — गंगा पूजन एवं पावन कलश स्थापन महा-अनुष्ठान",
      videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      thumbnail: "/images/ghat-kalash-procession.jpg",
      personOrPlace: "दशाश्वमेध घाट, काशी विश्वनाथ धाम",
      category: "program",
      state: "uttar-pradesh",
      district: "वाराणसी",
      duration: "18:45 Min",
      viewsCount: "24.1K",
      date: "22 जनवरी 2024",
      description:
        "काशी विश्वनाथ की पावन नगरी में मां गंगा के जल से कलश पूजन का अलौकिक दृश्य। निषादराज के स्वाभिमान और सनातन संस्कृति का भव्य संगम।",
      tag: "कार्यक्रम",
      order: 2,
    },
    {
      title: "समाज के गौरव और एकता पर ऐतिहासिक संबोधन — निषाद संकल्प सम्मेलन",
      videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      thumbnail: "/images/kalash-yatra-featured.jpg",
      personOrPlace: "डॉ. संजय निषाद / गांधी मैदान, पटना",
      category: "speech",
      state: "bihar",
      district: "पटना",
      duration: "26:10 Min",
      viewsCount: "32.8K",
      date: "05 फरवरी 2024",
      description:
        "पटना में आयोजित राज्यस्तरीय सम्मेलन में समाज के उत्थान, शिक्षा और संगठित शक्ति पर दिए गए ओजस्वी विचार।",
      tag: "संबोधन",
      order: 3,
    },
    {
      title: "भोपाल में नर्मदा जल कलश यात्रा — मध्य प्रदेश के हजारों श्रद्धालुओं का जनसैलाब",
      videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      thumbnail: "/images/sacred-kalash-ritual.jpg",
      personOrPlace: "नर्मदांचल समिति, वीआईपी रोड भोपाल",
      category: "yatra",
      state: "madhya-pradesh",
      district: "भोपाल",
      duration: "11:55 Min",
      viewsCount: "12.3K",
      date: "18 फरवरी 2024",
      description:
        "मां नर्मदा के पावन जल को साक्षी मानकर सामाजिक समरसता और स्वावलंबन का संकल्प लिया गया।",
      tag: "कलश यात्रा",
      order: 4,
    },
    {
      title: "रांची सुवर्णरेखा तट — झारखंड में पावन कलश यात्रा व सामाजिक चेतना सम्मेलन",
      videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      thumbnail: "/images/ranchi-kalash-procession.jpg",
      personOrPlace: "सुवर्णरेखा घाट, नामकुम रांची",
      category: "program",
      state: "jharkhand",
      district: "रांची",
      duration: "16:30 Min",
      viewsCount: "15.9K",
      date: "28 फरवरी 2024",
      description:
        "झारखंड के विभिन्न जिलों से पधारे समाजबंधुओं ने जल संरक्षण और सांस्कृतिक एकता की शपथ ली।",
      tag: "कार्यक्रम",
      order: 5,
    },
    {
      title: "लखनऊ में युवा शक्ति संवाद — शिक्षा, अधिकार और स्वाभिमान का पावन संकल्प",
      videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      thumbnail: "/images/ghat-kalash-procession.jpg",
      personOrPlace: "युवा मोर्चा सम्मेलन, हजरतगंज लखनऊ",
      category: "speech",
      state: "uttar-pradesh",
      district: "लखनऊ",
      duration: "21:05 Min",
      viewsCount: "29.4K",
      date: "10 मार्च 2024",
      description:
        "नई पीढ़ी को उच्च शिक्षा, प्रशासनिक सेवाओं व आत्मनिर्भरता से जोड़ने हेतु विस्तृत कार्ययोजना पर संबोधन।",
      tag: "संबोधन",
      order: 6,
    },
    {
      title: "प्रयागराज त्रिवेणी संगम — पावन जल कलश अर्चन व राष्ट्रीय एकता महा-संकल्प",
      videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      thumbnail: "/images/ghat-kalash-procession.jpg",
      personOrPlace: "त्रिवेणी संगम, प्रयागराज",
      category: "yatra",
      state: "uttar-pradesh",
      district: "प्रयागराज",
      duration: "15:40 Min",
      viewsCount: "21.7K",
      date: "15 मार्च 2024",
      description:
        "गंगा, यमुना और सरस्वती के पावन संगम पर हजारों मातृशक्तियों द्वारा मंगल कलश पूजन और सामाजिक सद्भाव का संकल्प।",
      tag: "कलश यात्रा",
      order: 7,
    },
    {
      title: "मुजफ्फरपुर पावन जन-आंदोलन — महिला स्वाभिमान व मंगल कलश शोभायात्रा",
      videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      thumbnail: "/images/kalash-yatra-featured.jpg",
      personOrPlace: "कंपनी बाग मैदान, मुजफ्फरपुर",
      category: "program",
      state: "bihar",
      district: "मुजफ्फरपुर",
      duration: "13:15 Min",
      viewsCount: "17.2K",
      date: "22 मार्च 2024",
      description:
        "उत्तर बिहार में सामाजिक चेतना का ऐतिहासिक शंखनाद, पारंपरिक परिधानों में महिलाओं का अभूतपूर्व उत्साह।",
      tag: "कार्यक्रम",
      order: 8,
    },
    {
      title: "जबलपुर भेड़ाघाट नर्मदा तट — महाआरती व पावन कलश यात्रा महाकुंभ",
      videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      thumbnail: "/images/sacred-kalash-ritual.jpg",
      personOrPlace: "भेड़ाघाट नर्मदा तट, जबलपुर",
      category: "yatra",
      state: "madhya-pradesh",
      district: "जबलपुर",
      duration: "17:50 Min",
      viewsCount: "19.8K",
      date: "02 अप्रैल 2024",
      description:
        "धुआंधार जलप्रपात के समीप वैदिक रीति से कलश पूजन, मां नर्मदा की महाआरती के साथ समाज जागरण का उद्घोष।",
      tag: "कलश यात्रा",
      order: 9,
    },
    {
      title: "अयोध्या धाम सरयू तट — पावन कलश पूजन व सांस्कृतिक चेतना जनसभा",
      videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      thumbnail: "/images/kalash-yatra-hero.jpg",
      personOrPlace: "राम की पैड़ी, अयोध्या धाम",
      category: "yatra",
      state: "uttar-pradesh",
      district: "अयोध्या",
      duration: "19:10 Min",
      viewsCount: "35.6K",
      date: "10 अप्रैल 2024",
      description:
        "पवित्र सरयू जल के साथ भव्य कलश यात्रा, प्रभु श्रीराम और निषादराज के अमर प्रेम व समरसता की गूंज।",
      tag: "कलश यात्रा",
      order: 10,
    },
    {
      title: "दरभंगा मिथिलांचल — भव्य कलश यात्रा व सामाजिक समरसता सम्मेलन",
      videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      thumbnail: "/images/kalash-yatra-featured.jpg",
      personOrPlace: "राज मैदान, दरभंगा",
      category: "program",
      state: "bihar",
      district: "दरभंगा",
      duration: "12:45 Min",
      viewsCount: "14.3K",
      date: "18 अप्रैल 2024",
      description:
        "मिथिला की पावन संस्कृति और शंखध्वनि के साथ संपन्न हुई भव्य कलश यात्रा, हजारों लोगों की भागीदारी।",
      tag: "कार्यक्रम",
      order: 11,
    },
    {
      title: "ग्वालियर चंबल संभाग — ऐतिहासिक कलश संकल्प व युवा जागृति रैली",
      videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      thumbnail: "/images/ranchi-kalash-procession.jpg",
      personOrPlace: "फूलबाग मैदान, ग्वालियर",
      category: "speech",
      state: "madhya-pradesh",
      district: "ग्वालियर",
      duration: "22:30 Min",
      viewsCount: "25.1K",
      date: "25 अप्रैल 2024",
      description:
        "चंबल अंचल के युवाओं को स्वाभिमान, शिक्षा और अधिकार की राह पर अग्रसर करने हेतु ऐतिहासिक प्रेरक संबोधन।",
      tag: "संबोधन",
      order: 12,
    },
    {
      title: "धनबाद कोयलांचल — दामोदर नदी तट पर पवित्र कलश स्थापन व प्रतिज्ञा",
      videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      thumbnail: "/images/sacred-kalash-ritual.jpg",
      personOrPlace: "दामोदर घाट, धनबाद",
      category: "yatra",
      state: "jharkhand",
      district: "धनबाद",
      duration: "14:55 Min",
      viewsCount: "16.4K",
      date: "04 मई 2024",
      description:
        "दामोदर नदी के पावन तट पर वैदिक मंत्रों के साथ कलश पूजन एवं समाज के सर्वांगीण विकास का संकल्प।",
      tag: "कलश यात्रा",
      order: 13,
    },
    {
      title: "गोरखपुर राप्ती तट — भव्य शोभायात्रा व समाज सशक्तिकरण उद्बोधन",
      videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      thumbnail: "/images/kalash-yatra-hero.jpg",
      personOrPlace: "गुरु गोरक्षनाथ घाट, गोरखपुर",
      category: "speech",
      state: "uttar-pradesh",
      district: "गोरखपुर",
      duration: "24:15 Min",
      viewsCount: "31.2K",
      date: "12 मई 2024",
      description:
        "पूर्वांचल के केंद्र गोरखपुर में सामाजिक समरसता, शिक्षा और संगठित संकल्प पर विशाल जनसभा को संबोधन।",
      tag: "संबोधन",
      order: 14,
    },
    {
      title: "गया पावन फल्गु तट — विष्णुपद दर्शन व मंगल कलश महा-संकल्प",
      videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      thumbnail: "/images/ghat-kalash-procession.jpg",
      personOrPlace: "विष्णुपद फल्गु घाट, गया",
      category: "yatra",
      state: "bihar",
      district: "गया",
      duration: "16:20 Min",
      viewsCount: "20.5K",
      date: "20 मई 2024",
      description:
        "मोक्षदायिनी गयाजी में पवित्र फल्गु जल का अर्चन, पितृ-तर्पण परंपरा और सामाजिक एकता की मंगल यात्रा।",
      tag: "कलश यात्रा",
      order: 15,
    },
    {
      title: "उज्जैन शिप्रा तट — महाकाल की पावन धरा पर कलश अभिषेक महा-सम्मेलन",
      videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      thumbnail: "/images/sacred-kalash-ritual.jpg",
      personOrPlace: "रामघाट शिप्रा तट, उज्जैन",
      category: "program",
      state: "madhya-pradesh",
      district: "उज्जैन",
      duration: "18:10 Min",
      viewsCount: "28.7K",
      date: "28 मई 2024",
      description:
        "द्वादश ज्योतिर्लिंग महाकाल नगरी में मां शिप्रा के अमृत जल से कलश अभिषेक और सामाजिक नवजागरण का शंखनाद।",
      tag: "कार्यक्रम",
      order: 16,
    },
    {
      title: "जयपुर गुलाबी नगरी — ऐतिहासिक जन-चेतना व स्वाभिमान कलश यात्रा",
      videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      thumbnail: "/images/kalash-yatra-featured.jpg",
      personOrPlace: "अल्बर्ट हॉल परिसर, जयपुर",
      category: "yatra",
      state: "rajasthan",
      district: "जयपुर",
      duration: "15:35 Min",
      viewsCount: "22.3K",
      date: "05 जून 2024",
      description:
        "राजस्थान की वीरधरा पर पारंपरिक लोक संस्कृति के साथ संपन्न हुई भव्य मंगल कलश शोभायात्रा।",
      tag: "कलश यात्रा",
      order: 17,
    },
    {
      title: "भागलपुर अंग प्रदेश — गंगा तट पर पावन कलश पूजन व विशाल जनसैलाब",
      videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      thumbnail: "/images/ghat-kalash-procession.jpg",
      personOrPlace: "बरारी घाट, भागलपुर",
      category: "yatra",
      state: "bihar",
      district: "भागलपुर",
      duration: "13:50 Min",
      viewsCount: "16.8K",
      date: "14 जून 2024",
      description:
        "दानवीर कर्ण की धरा पर उत्तरवाहिनी गंगा के जल से कलश पूजन, समाज के प्रत्येक वर्ग का अपार समर्थन।",
      tag: "कलश यात्रा",
      order: 18,
    },
    {
      title: "कोटा चंबल तट — युवा प्रेरणा संवाद व पावन मंगल कलश समारोह",
      videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      thumbnail: "/images/ranchi-kalash-procession.jpg",
      personOrPlace: "चंबल रिवर फ्रंट, कोटा",
      category: "speech",
      state: "rajasthan",
      district: "कोटा",
      duration: "20:40 Min",
      viewsCount: "23.9K",
      date: "22 जून 2024",
      description:
        "चंबल रिवर फ्रंट के समीप युवाओं को कौशल विकास, उच्च शिक्षा और आत्मनिर्भर समाज निर्माण हेतु मार्गदर्शन।",
      tag: "संबोधन",
      order: 19,
    },
    {
      title: "मिर्ज़ापुर विंध्याचल धाम — मां विंध्यवासिनी के आशीर्वाद से भव्य कलश परिक्रमा",
      videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      thumbnail: "/images/sacred-kalash-ritual.jpg",
      personOrPlace: "विंध्याचल गंगा घाट, मिर्ज़ापुर",
      category: "program",
      state: "uttar-pradesh",
      district: "मिर्ज़ापुर",
      duration: "16:05 Min",
      viewsCount: "26.4K",
      date: "30 जून 2024",
      description:
        "मां विंध्यवासिनी धाम में गंगा जल कलश पूजन, शक्ति आराधना और समाज कल्याण हेतु पावन अनुष्ठान।",
      tag: "कार्यक्रम",
      order: 20,
    },
  ],

  pillarsSection: {
    kicker: "Sacred Heritage & Social Awakening • Major Pledges Showcase",
    title: "Four Major Pledges of Kalash Yatra — ",
    titleAccent: "Faith, Culture and Self-Respect",
    subtitle:
      "A sacred movement for social harmony, women's empowerment, and a bright future for coming generations. Discover the core values of this campaign.",
    storyCollage: {
      primaryCard: {
        image: "/images/ghat-kalash-procession.jpg",
        badge: "Confluence of Ganga & Sacred Rivers",
        title: "Water Purification & Cultural Renaissance",
        desc: "Divine sight of women performing Kalash worship with Vedic chants at sunrise on sacred river banks.",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      },
      subCard1: {
        image: "/images/sacred-kalash-ritual.jpg",
        tag: "🪔 Vedic Ceremony",
        title: "Auspicious Kalash Installation",
        desc: "Mango leaves, coconut and sacred water",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      },
      subCard2: {
        image: "/images/kalash-yatra-featured.jpg",
        tag: "🚩 Historic Rally",
        title: "Call for Dignity & Unity",
        desc: "Unity across 150+ districts",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      },
    },
    pillars: [
      {
        number: "01",
        iconKey: "water",
        title: "Sacred Water & Environmental Conservation Pledge",
        description:
          "Witnessed by sacred rivers like Ganga, Saryu, Narmada and Gandak, taking a collective vow for clean water sources and ecological balance.",
        order: 1,
      },
      {
        number: "02",
        iconKey: "women",
        title: "Pride & Empowerment of Women",
        description:
          "Frontline leadership of mothers, sisters, and daughters in the Kalash Yatra, embodying womanhood's vital role in social leadership.",
        order: 2,
      },
      {
        number: "03",
        iconKey: "unity",
        title: "Social Harmony & Solid Unity",
        description:
          "Transcending boundaries of villages, towns, and states to unite every section into a single fabric of brotherhood and collective strength.",
        order: 3,
      },
      {
        number: "04",
        iconKey: "education",
        title: "Path to Education, Values & Self-Reliance",
        description:
          "Connecting the youth to their proud historical legacy, promoting higher education, and building a self-reliant community.",
        order: 4,
      },
    ],
  },

  democraticPledge: {
    enabled: true,
    badge: "🇮🇳 ऐतिहासिक लोकतांत्रिक महा-संकल्प",
    title: "लोकतांत्रिक संकल्प पत्र",
    subtitle: "स्वतंत्र विचार, स्वाभिमान एवं जनमत का संवैधानिक अधिकार",
    pledgeText:
      "आज हम लोकतांत्रिक संकल्प लेते हैं कि आगामी चुनाव में भाजपा के पक्ष में मतदान नहीं करेंगे तथा अपने विवेक और विचार के आधार पर अपने मताधिकार का प्रयोग करेंगे।",
    signOff: "— समस्त समाज, युवा एवं मातृशक्ति का सामूहिक संकल्प",
    keyPoints: [
      "मतदान हमारा संवैधानिक अधिकार और स्वाभिमान का प्रतीक है",
      "समाज के समग्र हितों, विकास और मान-सम्मान को ध्यान में रखकर ही वोट देंगे",
      "किसी भी अनुचित दबाव या बहकावे में न आकर स्वतंत्र विवेक से निर्णय लेंगे",
    ],
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
  },
};

const kalashYatraSchema = new mongoose.Schema(
  {
    hero: {
      liveBadgeText: { type: String, default: defaultKalashYatraData.hero.liveBadgeText },
      headingMain: { type: String, default: defaultKalashYatraData.hero.headingMain },
      headingHighlight: { type: String, default: defaultKalashYatraData.hero.headingHighlight },
      subheading: { type: String, default: defaultKalashYatraData.hero.subheading },
      highlights: [{ type: String }],
      primaryBtnText: { type: String, default: defaultKalashYatraData.hero.primaryBtnText },
      primaryBtnLink: { type: String, default: defaultKalashYatraData.hero.primaryBtnLink },
      secondaryBtnText: { type: String, default: defaultKalashYatraData.hero.secondaryBtnText },
      secondaryBtnLink: { type: String, default: defaultKalashYatraData.hero.secondaryBtnLink },
      stats: [
        {
          number: { type: String, default: "" },
          label: { type: String, default: "" },
          sub: { type: String, default: "" },
        },
      ],
      featuredVideo: {
        title: { type: String, default: defaultKalashYatraData.hero.featuredVideo.title },
        duration: { type: String, default: defaultKalashYatraData.hero.featuredVideo.duration },
        videoUrl: { type: String, default: defaultKalashYatraData.hero.featuredVideo.videoUrl },
        posterImage: { type: String, default: defaultKalashYatraData.hero.featuredVideo.posterImage },
        badge: { type: String, default: defaultKalashYatraData.hero.featuredVideo.badge },
      },
    },

    milestonesSection: {
      kicker: { type: String, default: defaultKalashYatraData.milestonesSection.kicker },
      title: { type: String, default: defaultKalashYatraData.milestonesSection.title },
      titleHighlight: { type: String, default: defaultKalashYatraData.milestonesSection.titleHighlight },
      subtitle: { type: String, default: defaultKalashYatraData.milestonesSection.subtitle },
      items: [
        {
          stateKey: { type: String, default: "bihar" },
          stateName: { type: String, default: "" },
          district: { type: String, default: "" },
          title: { type: String, default: "" },
          image: { type: String, default: "" },
          description: { type: String, default: "" },
          tag: { type: String, default: "" },
          videoUrl: { type: String, default: "" },
          order: { type: Number, default: 0 },
        },
      ],
    },

    videos: [
      {
        title: { type: String, required: true },
        videoUrl: { type: String, required: true },
        thumbnail: { type: String, default: "" },
        personOrPlace: { type: String, default: "" },
        category: {
          type: String,
          enum: ["all", "yatra", "program", "speech"],
          default: "yatra",
        },
        state: { type: String, default: "bihar" },
        district: { type: String, default: "" },
        duration: { type: String, default: "10:00 Min" },
        viewsCount: { type: String, default: "10K" },
        date: { type: String, default: "" },
        description: { type: String, default: "" },
        tag: { type: String, default: "Kalash Yatra" },
        order: { type: Number, default: 0 },
      },
    ],

    pillarsSection: {
      kicker: { type: String, default: defaultKalashYatraData.pillarsSection.kicker },
      title: { type: String, default: defaultKalashYatraData.pillarsSection.title },
      titleAccent: { type: String, default: defaultKalashYatraData.pillarsSection.titleAccent },
      subtitle: { type: String, default: defaultKalashYatraData.pillarsSection.subtitle },
      storyCollage: {
        primaryCard: {
          image: { type: String, default: "" },
          badge: { type: String, default: "" },
          title: { type: String, default: "" },
          desc: { type: String, default: "" },
          videoUrl: { type: String, default: "" },
        },
        subCard1: {
          image: { type: String, default: "" },
          tag: { type: String, default: "" },
          title: { type: String, default: "" },
          desc: { type: String, default: "" },
          videoUrl: { type: String, default: "" },
        },
        subCard2: {
          image: { type: String, default: "" },
          tag: { type: String, default: "" },
          title: { type: String, default: "" },
          desc: { type: String, default: "" },
          videoUrl: { type: String, default: "" },
        },
      },
      pillars: [
        {
          number: { type: String, default: "" },
          iconKey: { type: String, default: "water" },
          title: { type: String, default: "" },
          description: { type: String, default: "" },
          order: { type: Number, default: 0 },
        },
      ],
    },

    democraticPledge: {
      enabled: { type: Boolean, default: true },
      badge: { type: String, default: "🇮🇳 ऐतिहासिक लोकतांत्रिक महा-संकल्प" },
      title: { type: String, default: "लोकतांत्रिक संकल्प पत्र" },
      subtitle: { type: String, default: "स्वतंत्र विचार, स्वाभिमान एवं जनमत का संवैधानिक अधिकार" },
      pledgeText: {
        type: String,
        default:
          "आज हम लोकतांत्रिक संकल्प लेते हैं कि आगामी चुनाव में भाजपा के पक्ष में मतदान नहीं करेंगे तथा अपने विवेक और विचार के आधार पर अपने मताधिकार का प्रयोग करेंगे।",
      },
      signOff: { type: String, default: "— समस्त समाज, युवा एवं मातृशक्ति का सामूहिक संकल्प" },
      keyPoints: [{ type: String }],
      videoUrl: { type: String, default: "" },
    },
  },
  { timestamps: true }
);

// Static helper to get existing doc or seed if empty
kalashYatraSchema.statics.getOrSeed = async function () {
  let doc = await this.findOne();
  if (!doc) {
    doc = await this.create(defaultKalashYatraData);
    console.log("🌱 Default Kalash Yatra content seeded successfully.");
  }
  return doc;
};

kalashYatraSchema.statics.defaultData = defaultKalashYatraData;

module.exports = mongoose.model("KalashYatra", kalashYatraSchema);
