const mongoose = require("mongoose");

const defaultKalashYatraData = {
  hero: {
    liveBadgeText: "संकल्प यात्रा और मतदाता जागरूकता",
    headingMain: "जन-जन का संकल्प — लोकतंत्र को मजबूत बनाने का संकल्प",
    headingHighlight: "स्वतंत्र मतदान, स्वाभिमान और सामाजिक चेतना",
    subheading:
      "आज हम लोकतांत्रिक संकल्प लेते हैं कि आगामी चुनाव में भाजपा के पक्ष में मतदान नहीं करेंगे तथा अपने विवेक और विचार के आधार पर अपने मताधिकार का प्रयोग करेंगे।",
    highlights: [
      "लोकतांत्रिक अधिकारों और स्वतंत्र मताधिकार की रक्षा",
      "सामाजिक न्याय, स्वाभिमान और जन-जागरण का महा-संकल्प",
      "बिना किसी भय या प्रलोभन के स्वतंत्र मतदान का आह्वान",
    ],
    primaryBtnText: "संकल्प वीडियो संकलन देखें",
    primaryBtnLink: "#videoGallery",
    secondaryBtnText: "राज्य व जिला चुनें",
    secondaryBtnLink: "#filterConsole",
    stats: [
      { number: "150+", label: "जिलों में विस्तार", sub: "पवित्र संकल्प यात्रा" },
      { number: "50,000+", label: "सहमति संकल्प", sub: "जन-जागरण अभियान" },
      { number: "10,000+", label: "मातृशक्ति सहभागिता", sub: "अग्रिम पंक्ति में" },
      { number: "28+", label: "राज्यों में चेतना", sub: "अखंड राष्ट्रीय अभियान" },
    ],
    featuredVideo: {
      title: "ऐतिहासिक लोकतांत्रिक महा-संकल्प यात्रा — भव्य जनमत उद्घोष",
      duration: "12:45 Min",
      videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      posterImage: "/images/kalash-yatra-hero.jpg",
      badge: "★ विशेष प्रस्तुति",
    },
  },

  milestonesSection: {
    kicker: "★ ऐतिहासिक जन-संकल्प • लोकतांत्रिक अधिकार चेतना अभियान • ऐतिहासिक महासंगम",
    title: "लोकतांत्रिक महा-संकल्प यात्रा — ",
    titleHighlight: "जागरूक मतदाता और स्वतंत्र मताधिकार का संदेश",
    subtitle:
      "आज हम लोकतांत्रिक संकल्प लेते हैं कि आगामी चुनाव में भाजपा के पक्ष में मतदान नहीं करेंगे तथा अपने विवेक और विचार के आधार पर अपने मताधिकार का प्रयोग करेंगे।",
    items: [
      {
        stateKey: "bihar",
        stateName: "बिहार",
        district: "गोपालगंज",
        title: "गोपालगंज में ऐतिहासिक लोकतांत्रिक महा-संकल्प सम्मेलन",
        image: "/images/democratic-pledge-featured.jpg",
        description:
          "हजारों नागरिकों और मातृशक्तियों ने शपथ ली: आगामी चुनाव में भाजपा के पक्ष में मतदान नहीं करेंगे तथा अपने विवेक और विचार के आधार पर अपने मताधिकार का प्रयोग करेंगे।",
        tag: "🚩 महा-संकल्प उद्घोष",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        order: 1,
      },
      {
        stateKey: "uttar-pradesh",
        stateName: "उत्तर प्रदेश",
        district: "वाराणसी घाट",
        title: "वाराणसी दशाश्वमेध घाट — स्वतंत्र मताधिकार का पावन महा-संकल्प",
        image: "/images/democratic-pledge-varanasi.jpg",
        description:
          "पवित्र गंगा तट पर हजारों माताओं-बहनों और नागरिकों ने सहभागिता करते हुए जागरूकता, सामाजिक एकता और स्वतंत्र मताधिकार के प्रति अपनी प्रतिबद्धता का संकल्प लिया।",
        tag: "🪔 लोकतांत्रिक जन-जागरण",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        order: 2,
      },
      {
        stateKey: "uttar-pradesh",
        stateName: "उत्तर प्रदेश",
        district: "अयोध्या - प्रयागराज",
        title: "गांधी मैदान पटना — युवा शक्ति का लोकतांत्रिक शंखनाद",
        image: "/images/democratic-pledge-patna.jpg",
        description:
          "पवित्र संगम तट पर नागरिकों ने एकजुट होकर सामाजिक समरसता, जन-जागरण और स्वतंत्र मताधिकार के प्रति अपनी प्रतिबद्धता व्यक्त करते हुए लोकतांत्रिक संकल्प लिया।",
        tag: "⚡ युवा जनमत जागृति",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        order: 3,
      },
      {
        stateKey: "madhya-pradesh",
        stateName: "मध्य प्रदेश",
        district: "भोपाल",
        title: "भोपाल नर्मदांचल — सामाजिक अधिकार व स्वतंत्र जनमत महा-अधिवेशन",
        image: "/images/democratic-pledge-bhopal.jpg",
        description:
          "मध्य प्रदेश के कोने-कोने से जुटे जनसमूह ने अपने संवैधानिक अधिकारों की रक्षा और विवेकपूर्ण मतदान की ऐतिहासिक प्रतिज्ञा ली।",
        tag: "🏛️ महा-अधिवेशन",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        order: 4,
      },
      {
        stateKey: "jharkhand",
        stateName: "झारखंड",
        district: "रांची",
        title: "रांची सुवर्णरेखा तट — स्वाभिमान व स्वतंत्र मतदान महा-सभा",
        image: "/images/democratic-pledge-ranchi.jpg",
        description:
          "जल, जंगल, जमीन और जनमत के सम्मान के लिए आगामी चुनाव में निष्पक्ष व स्वतंत्र निर्णय लेने की शपथ ली गई।",
        tag: "🌿 स्वाभिमान महा-संकल्प",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        order: 5,
      },
    ],
  },

  videos: [
  {
    "title": "गोपालगंज ऐतिहासिक लोकतांत्रिक संकल्प महासम्मेलन — स्वतंत्र मतदान का सामूहिक आह्वान",
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "thumbnail": "/images/kalash-yatra-featured.jpg",
    "personOrPlace": "मुख्य चौक, गोपालगंज",
    "peopleCount": "15,000+ लोग",
    "category": "sankalp",
    "state": "bihar",
    "district": "गोपालगंज",
    "duration": "14:20 Min",
    "viewsCount": "18.5K",
    "date": "14 जनवरी 2024",
    "description": "आज हम लोकतांत्रिक संकल्प लेते हैं कि आगामी चुनाव में भाजपा के पक्ष में मतदान नहीं करेंगे तथा अपने विवेक और विचार के आधार पर अपने मताधिकार का प्रयोग करेंगे।",
    "tag": "महा-संकल्प",
    "order": 1
  },
  {
    "title": "गोपालगंज विशाल जनसभा — 5000+ नागरिकों का लोकतांत्रिक संकल्प उद्घोष",
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "thumbnail": "/images/kalash-yatra-hero.jpg",
    "personOrPlace": "मातृशक्ति सम्मेलन, गोपालगंज",
    "peopleCount": "5,000+ लोग",
    "category": "sankalp",
    "state": "bihar",
    "district": "गोपालगंज",
    "duration": "15:40 Min",
    "viewsCount": "22.4K",
    "date": "18 जनवरी 2024",
    "description": "आज हम लोकतांत्रिक संकल्प लेते हैं कि आगामी चुनाव में भाजपा के पक्ष में मतदान नहीं करेंगे तथा अपने विवेक और विचार के आधार पर अपने मताधिकार का प्रयोग करेंगे। समाज के उत्थान, शिक्षा और स्वाभिमान का ऐतिहासिक संकल्प।",
    "tag": "महा-संकल्प",
    "order": 2
  },
  {
    "title": "वाराणसी दशाश्वमेध घाट — स्वतंत्र मतदान और स्वाभिमान की पावन प्रतिज्ञा",
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "thumbnail": "/images/ghat-kalash-procession.jpg",
    "personOrPlace": "दशाश्वमेध घाट, काशी विश्वनाथ धाम",
    "peopleCount": "25,000+ लोग",
    "category": "program",
    "state": "uttar-pradesh",
    "district": "वाराणसी",
    "duration": "18:45 Min",
    "viewsCount": "24.1K",
    "date": "22 जनवरी 2024",
    "description": "काशी की पावन धरा पर जनता का लोकतांत्रिक संकल्प: आगामी चुनाव में भाजपा के पक्ष में मतदान नहीं करेंगे तथा स्वतंत्र विवेक और विचार से मतदान करेंगे।",
    "tag": "कार्यक्रम",
    "order": 3
  },
  {
    "title": "गांधी मैदान पटना — युवा शक्ति संवाद, मताधिकार का स्वतंत्र प्रयोग करने पर संबोधन",
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "thumbnail": "/images/kalash-yatra-featured.jpg",
    "personOrPlace": "गांधी मैदान, पटना",
    "peopleCount": "35,000+ लोग",
    "category": "speech",
    "state": "bihar",
    "district": "पटना",
    "duration": "26:10 Min",
    "viewsCount": "32.8K",
    "date": "05 फरवरी 2024",
    "description": "पटना में आयोजित राज्यस्तरीय सम्मेलन में समाज के उत्थान, शिक्षा और स्वतंत्र जनमत पर दिए गए ओजस्वी विचार। आज हम लोकतांत्रिक संकल्प लेते हैं कि आगामी चुनाव में भाजपा के पक्ष में मतदान नहीं करेंगे तथा अपने विवेक और विचार के आधार पर अपने मताधिकार का प्रयोग करेंगे।",
    "tag": "संबोधन",
    "order": 4
  },
  {
    "title": "भोपाल नर्मदांचल जनसैलाब — लोकतांत्रिक संकल्प लेते हुए हजारों नागरिकों की गर्जना",
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "thumbnail": "/images/sacred-kalash-ritual.jpg",
    "personOrPlace": "नर्मदांचल समिति, वीआईपी रोड भोपाल",
    "peopleCount": "12,000+ लोग",
    "category": "sankalp",
    "state": "madhya-pradesh",
    "district": "भोपाल",
    "duration": "11:55 Min",
    "viewsCount": "12.3K",
    "date": "18 फरवरी 2024",
    "description": "आज हम लोकतांत्रिक संकल्प लेते हैं कि आगामी चुनाव में भाजपा के पक्ष में मतदान नहीं करेंगे तथा अपने विवेक और विचार के आधार पर अपने मताधिकार का प्रयोग करेंगे।",
    "tag": "महा-संकल्प",
    "order": 5
  },
  {
    "title": "रांची सुवर्णरेखा तट — स्वतंत्र जनमत व स्वाभिमान अधिकार प्रतिज्ञा सम्मेलन",
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "thumbnail": "/images/ranchi-kalash-procession.jpg",
    "personOrPlace": "सुवर्णरेखा घाट, नामकुम रांची",
    "peopleCount": "18,000+ लोग",
    "category": "program",
    "state": "jharkhand",
    "district": "रांची",
    "duration": "16:30 Min",
    "viewsCount": "15.9K",
    "date": "28 फरवरी 2024",
    "description": "झारखंड में आयोजित विशाल जन-एकता सम्मेलन में समाज के हर वर्ग ने लोकतांत्रिक संकल्प पत्र को आत्मसात किया और निष्पक्ष मतदान की शपथ ली।",
    "tag": "कार्यक्रम",
    "order": 6
  },
  {
    "title": "लखनऊ युवा चेतना संवाद — स्वतंत्र मताधिकार, शिक्षा व स्वाभिमान का संकल्प",
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "thumbnail": "/images/ghat-kalash-procession.jpg",
    "personOrPlace": "युवा मोर्चा सम्मेलन, हजरतगंज लखनऊ",
    "peopleCount": "20,000+ लोग",
    "category": "speech",
    "state": "uttar-pradesh",
    "district": "लखनऊ",
    "duration": "21:05 Min",
    "viewsCount": "29.4K",
    "date": "10 मार्च 2024",
    "description": "राजधानी लखनऊ में युवाओं का ऐतिहासिक लोकतांत्रिक संकल्प: आगामी चुनाव में भाजपा के पक्ष में मतदान नहीं करेंगे तथा अपने विवेक और विचार से मतदान करेंगे।",
    "tag": "संबोधन",
    "order": 7
  },
  {
    "title": "प्रयागराज त्रिवेणी संगम — स्वतंत्र जनमत व सामाजिक न्याय महा-संकल्प सभा",
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "thumbnail": "/images/ghat-kalash-procession.jpg",
    "personOrPlace": "त्रिवेणी संगम, प्रयागराज",
    "peopleCount": "30,000+ लोग",
    "category": "sankalp",
    "state": "uttar-pradesh",
    "district": "प्रयागराज",
    "duration": "15:40 Min",
    "viewsCount": "21.7K",
    "date": "15 मार्च 2024",
    "description": "पवित्र त्रिवेणी संगम पर नागरिकों ने लोकतांत्रिक संकल्प लेते हुए आह्वान किया कि आगामी चुनाव में स्वतंत्र विवेक से अपने मताधिकार का प्रयोग करेंगे। आज हम लोकतांत्रिक संकल्प लेते हैं कि आगामी चुनाव में भाजपा के पक्ष में मतदान नहीं करेंगे तथा अपने विवेक और विचार के आधार पर अपने मताधिकार का प्रयोग करेंगे।",
    "tag": "महा-संकल्प",
    "order": 8
  },
  {
    "title": "मुजफ्फरपुर मातृशक्ति सम्मेलन — अधिकार, स्वाभिमान व लोकतांत्रिक संकल्प",
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "thumbnail": "/images/kalash-yatra-featured.jpg",
    "personOrPlace": "कंपनी बाग मैदान, मुजफ्फरपुर",
    "peopleCount": "10,000+ लोग",
    "category": "program",
    "state": "bihar",
    "district": "मुजफ्फरपुर",
    "duration": "13:15 Min",
    "viewsCount": "17.2K",
    "date": "22 मार्च 2024",
    "description": "उत्तर बिहार में महिलाओं का ऐतिहासिक जन-आंदोलन। स्वतंत्र सोच और निष्पक्ष मताधिकार के साथ अपने अधिकारों की रक्षा का सामूहिक संकल्प लिया।",
    "tag": "कार्यक्रम",
    "order": 9
  },
  {
    "title": "जबलपुर भेड़ाघाट नर्मदा तट — स्वतंत्र मतदान व जन-जागृति महा-अधिवेशन",
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "thumbnail": "/images/sacred-kalash-ritual.jpg",
    "personOrPlace": "भेड़ाघाट नर्मदा तट, जबलपुर",
    "peopleCount": "15,000+ लोग",
    "category": "sankalp",
    "state": "madhya-pradesh",
    "district": "जबलपुर",
    "duration": "17:50 Min",
    "viewsCount": "19.8K",
    "date": "02 अप्रैल 2024",
    "description": "नर्मदांचल के हजारों नागरिकों ने ऐतिहासिक संकल्प लिया: आगामी चुनाव में भाजपा के पक्ष में मतदान नहीं करेंगे तथा अपने स्वतंत्र विवेक के आधार पर मतदान करेंगे।",
    "tag": "महा-संकल्प",
    "order": 10
  },
  {
    "title": "अयोध्या धाम सरयू तट — जनमत चेतना व स्वाभिमान अधिकार जनसभा",
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "thumbnail": "/images/kalash-yatra-hero.jpg",
    "personOrPlace": "राम की पैड़ी, अयोध्या धाम",
    "peopleCount": "40,000+ लोग",
    "category": "program",
    "state": "uttar-pradesh",
    "district": "अयोध्या",
    "duration": "19:10 Min",
    "viewsCount": "35.6K",
    "date": "10 अप्रैल 2024",
    "description": "पवित्र सरयू जल के साक्षी में हजारों लोगों ने लोकतांत्रिक संकल्प लिया कि समाज के हितों, स्वाभिमान और अधिकारों के लिए निष्पक्ष मतदान करेंगे।",
    "tag": "कार्यक्रम",
    "order": 11
  },
  {
    "title": "दरभंगा मिथिलांचल — लोकतांत्रिक अधिकार व स्वतंत्र जनमत महा-सम्मेलन",
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "thumbnail": "/images/kalash-yatra-featured.jpg",
    "personOrPlace": "राज मैदान, दरभंगा",
    "peopleCount": "16,000+ लोग",
    "category": "program",
    "state": "bihar",
    "district": "दरभंगा",
    "duration": "12:45 Min",
    "viewsCount": "14.3K",
    "date": "18 अप्रैल 2024",
    "description": "मिथिलांचल की धरती पर समाज के प्रबुद्ध नागरिकों ने संकल्प लिया कि आगामी चुनाव में किसी भी दबाव में न आकर स्वतंत्र विवेक से वोट करेंगे। आज हम लोकतांत्रिक संकल्प लेते हैं कि आगामी चुनाव में भाजपा के पक्ष में मतदान नहीं करेंगे तथा अपने विवेक और विचार के आधार पर अपने मताधिकार का प्रयोग करेंगे।",
    "tag": "कार्यक्रम",
    "order": 12
  },
  {
    "title": "ग्वालियर चंबल संभाग — युवा जागृति रैली व लोकतांत्रिक संकल्प उद्बोधन",
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "thumbnail": "/images/ranchi-kalash-procession.jpg",
    "personOrPlace": "फूलबाग मैदान, ग्वालियर",
    "peopleCount": "22,000+ लोग",
    "category": "speech",
    "state": "madhya-pradesh",
    "district": "ग्वालियर",
    "duration": "22:30 Min",
    "viewsCount": "25.1K",
    "date": "25 अप्रैल 2024",
    "description": "चंबल अंचल के युवाओं का ओजस्वी संकल्प: अपने संवैधानिक अधिकारों की रक्षा करेंगे तथा आगामी चुनाव में भाजपा के पक्ष में मतदान न कर विवेक से निर्णय लेंगे।",
    "tag": "संबोधन",
    "order": 13
  },
  {
    "title": "धनबाद कोयलांचल — स्वतंत्र मताधिकार व सामाजिक स्वाभिमान जन-सभा",
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "thumbnail": "/images/sacred-kalash-ritual.jpg",
    "personOrPlace": "दामोदर घाट, धनबाद",
    "peopleCount": "14,000+ लोग",
    "category": "program",
    "state": "jharkhand",
    "district": "धनबाद",
    "duration": "14:55 Min",
    "viewsCount": "16.4K",
    "date": "04 मई 2024",
    "description": "दामोदर तट पर श्रमिकों व नागरिकों का विशाल संगम। स्वतंत्र जनमत और समाज कल्याण हेतु एकजुट होकर मतदान करने की शपथ ली।",
    "tag": "कार्यक्रम",
    "order": 14
  },
  {
    "title": "गोरखपुर राप्ती तट — जनमत जागरण व सामाजिक सशक्तिकरण महा-संबोधन",
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "thumbnail": "/images/kalash-yatra-hero.jpg",
    "personOrPlace": "गुरु गोरक्षनाथ घाट, गोरखपुर",
    "peopleCount": "28,000+ लोग",
    "category": "speech",
    "state": "uttar-pradesh",
    "district": "गोरखपुर",
    "duration": "24:15 Min",
    "viewsCount": "31.2K",
    "date": "12 मई 2024",
    "description": "पूर्वांचल में सामाजिक चेतना का शंखनाद: आज हम लोकतांत्रिक संकल्प लेते हैं कि आगामी चुनाव में भाजपा के पक्ष में मतदान नहीं करेंगे तथा अपने विवेक और विचार से मतदान करेंगे।",
    "tag": "संबोधन",
    "order": 15
  },
  {
    "title": "गया फल्गु तट — विष्णुपद धाम में लोकतांत्रिक स्वाभिमान महा-संकल्प",
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "thumbnail": "/images/ghat-kalash-procession.jpg",
    "personOrPlace": "विष्णुपद फल्गु घाट, गया",
    "peopleCount": "18,000+ लोग",
    "category": "sankalp",
    "state": "bihar",
    "district": "गया",
    "duration": "16:20 Min",
    "viewsCount": "20.5K",
    "date": "20 मई 2024",
    "description": "मोक्षनगरी गयाजी में हजारों नागरिकों ने सामूहिक संकल्प लिया: समाज के स्वाभिमान और अधिकारों के लिए स्वतंत्र विवेक से मताधिकार का प्रयोग करेंगे। आज हम लोकतांत्रिक संकल्प लेते हैं कि आगामी चुनाव में भाजपा के पक्ष में मतदान नहीं करेंगे तथा अपने विवेक और विचार के आधार पर अपने मताधिकार का प्रयोग करेंगे।",
    "tag": "महा-संकल्प",
    "order": 16
  },
  {
    "title": "उज्जैन शिप्रा तट — जनमत अधिकार व स्वतंत्र मतदान महा-सम्मेलन",
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "thumbnail": "/images/sacred-kalash-ritual.jpg",
    "personOrPlace": "रामघाट शिप्रा तट, उज्जैन",
    "peopleCount": "26,000+ लोग",
    "category": "program",
    "state": "madhya-pradesh",
    "district": "उज्जैन",
    "duration": "18:10 Min",
    "viewsCount": "28.7K",
    "date": "28 मई 2024",
    "description": "महाकाल की नगरी में जन-चेतना का ऐतिहासिक समागम। समाज के प्रत्येक वर्ग ने स्वतंत्र विचार व निष्पक्ष मतदान का लोकतांत्रिक संकल्प लिया।",
    "tag": "कार्यक्रम",
    "order": 17
  },
  {
    "title": "जयपुर गुलाबी नगरी — स्वाभिमान व लोकतांत्रिक जनमत अधिकार रैली",
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "thumbnail": "/images/kalash-yatra-featured.jpg",
    "personOrPlace": "अल्बर्ट हॉल परिसर, जयपुर",
    "peopleCount": "20,000+ लोग",
    "category": "sankalp",
    "state": "rajasthan",
    "district": "जयपुर",
    "duration": "15:35 Min",
    "viewsCount": "22.3K",
    "date": "05 जून 2024",
    "description": "राजस्थान की वीरधरा पर हजारों नागरिकों ने संकल्प लिया: आगामी चुनाव में भाजपा के पक्ष में मतदान नहीं करेंगे तथा अपने विवेक और विचार से मतदान करेंगे।",
    "tag": "महा-संकल्प",
    "order": 18
  },
  {
    "title": "भागलपुर अंग प्रदेश — स्वतंत्र मताधिकार व समाज चेतना जनसैलाब",
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "thumbnail": "/images/ghat-kalash-procession.jpg",
    "personOrPlace": "बरारी घाट, भागलपुर",
    "peopleCount": "15,000+ लोग",
    "category": "program",
    "state": "bihar",
    "district": "भागलपुर",
    "duration": "13:50 Min",
    "viewsCount": "16.8K",
    "date": "14 जून 2024",
    "description": "उत्तरवाहिनी गंगा के तट पर हजारों प्रबुद्ध नागरिकों ने अपने संवैधानिक अधिकारों की रक्षा और निष्पक्ष मतदान का पावन संकल्प लिया। आज हम लोकतांत्रिक संकल्प लेते हैं कि आगामी चुनाव में भाजपा के पक्ष में मतदान नहीं करेंगे तथा अपने विवेक और विचार के आधार पर अपने मताधिकार का प्रयोग करेंगे।",
    "tag": "कार्यक्रम",
    "order": 19
  },
  {
    "title": "कोटा चंबल तट — युवा प्रेरणा संवाद व स्वतंत्र मतदान चेतना समारोह",
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "thumbnail": "/images/ranchi-kalash-procession.jpg",
    "personOrPlace": "चंबल रिवर फ्रंट, कोटा",
    "peopleCount": "25,000+ लोग",
    "category": "speech",
    "state": "rajasthan",
    "district": "कोटा",
    "duration": "20:40 Min",
    "viewsCount": "23.9K",
    "date": "22 जून 2024",
    "description": "कोटा में युवा शक्ति का ऐतिहासिक समागम: अपने भविष्य और समाज के अधिकारों को ध्यान में रखकर स्वतंत्र विवेक से मताधिकार का प्रयोग करने का संकल्प।",
    "tag": "संबोधन",
    "order": 20
  },
  {
    "title": "मिर्ज़ापुर विंध्याचल धाम — गंगा तट पर लोकतांत्रिक संकल्प व अधिकार जनसभा",
    "videoUrl": "https://www.youtube.com/embed/dQw4w9WgXcQ",
    "thumbnail": "/images/sacred-kalash-ritual.jpg",
    "personOrPlace": "विंध्याचल गंगा घाट, मिर्ज़ापुर",
    "peopleCount": "30,000+ लोग",
    "category": "sankalp",
    "state": "uttar-pradesh",
    "district": "मिर्ज़ापुर",
    "duration": "16:05 Min",
    "viewsCount": "26.4K",
    "date": "30 जून 2024",
    "description": "मां विंध्यवासिनी धाम के समीप नागरिकों का विशाल समागम। स्वाभिमान, एकता और आगामी चुनाव में स्वतंत्र विवेक से मतदान करने का पावन संकल्प।",
    "tag": "महा-संकल्प",
    "order": 21
  }
  ],

  pillarsSection: {
    kicker: "Sacred Heritage & Social Awakening • Major Pledges Showcase",
    title: "Four Major Pledges of Sankalp Yatra — ",
    titleAccent: "Faith, Culture and Self-Respect",
    subtitle:
      "A sacred movement for social harmony, women's empowerment, and a bright future for coming generations. Discover the core values of this campaign.",
    storyCollage: {
      primaryCard: {
        image: "/images/ghat-kalash-procession.jpg",
        badge: "Confluence of Ganga & Sacred Rivers",
        title: "Water Purification & Cultural Renaissance",
        desc: "Divine sight of women performing Kalash worship with Vedic chants at sunrise on sacred river banks.",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      },
      subCard1: {
        image: "/images/sacred-kalash-ritual.jpg",
        tag: "🪔 Vedic Ceremony",
        title: "Auspicious Kalash Installation",
        desc: "Mango leaves, coconut and sacred water",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      },
      subCard2: {
        image: "/images/kalash-yatra-featured.jpg",
        tag: "🚩 Historic Rally",
        title: "Call for Dignity & Unity",
        desc: "Unity across 150+ districts",
        videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
      },
    },
    pillars: [
      {
        number: "01",
        iconKey: "water",
        title: "Sacred Water & Environmental Conservation Pledge",
        description:
          "Witnessed by sacred rivers like Ganga, Saryu, Narmada and Gandak, taking a collective vow for clean water sources and ecological balance.",
        order: 1,
      },
      {
        number: "02",
        iconKey: "women",
        title: "Pride & Empowerment of Women",
        description:
          "Frontline leadership of mothers, sisters, and daughters in the Sankalp Yatra, embodying womanhood's vital role in social leadership.",
        order: 2,
      },
      {
        number: "03",
        iconKey: "unity",
        title: "Social Harmony & Solid Unity",
        description:
          "Transcending boundaries of villages, towns, and states to unite every section into a single fabric of brotherhood and collective strength.",
        order: 3,
      },
      {
        number: "04",
        iconKey: "education",
        title: "Path to Education, Values & Self-Reliance",
        description:
          "Connecting the youth to their proud historical legacy, promoting higher education, and building a self-reliant community.",
        order: 4,
      },
    ],
  },

  democraticPledge: {
    enabled: true,
    badge: "🇮🇳 ऐतिहासिक लोकतांत्रिक महा-संकल्प",
    title: "लोकतांत्रिक संकल्प पत्र",
    subtitle: "स्वतंत्र विचार, स्वाभिमान एवं जनमत का संवैधानिक अधिकार",
    pledgeText:
      "आज हम लोकतांत्रिक संकल्प लेते हैं कि आगामी चुनाव में भाजपा के पक्ष में मतदान नहीं करेंगे तथा अपने विवेक और विचार के आधार पर अपने मताधिकार का प्रयोग करेंगे।",
    signOff: "— समस्त समाज, युवा एवं मातृशक्ति का सामूहिक संकल्प",
    keyPoints: [
      "मतदान हमारा संवैधानिक अधिकार और स्वाभिमान का प्रतीक है",
      "समाज के समग्र हितों, विकास और मान-सम्मान को ध्यान में रखकर ही वोट देंगे",
      "किसी भी अनुचित दबाव या बहकावे में न आकर स्वतंत्र विवेक से निर्णय लेंगे",
    ],
    videoUrl: "https://www.youtube.com/embed/dQw4w9WgXcQ",
  },
};

const kalashYatraSchema = new mongoose.Schema(
  {
    hero: {
      liveBadgeText: { type: String, default: defaultKalashYatraData.hero.liveBadgeText },
      headingMain: { type: String, default: defaultKalashYatraData.hero.headingMain },
      headingHighlight: { type: String, default: defaultKalashYatraData.hero.headingHighlight },
      subheading: { type: String, default: defaultKalashYatraData.hero.subheading },
      highlights: [{ type: String }],
      primaryBtnText: { type: String, default: defaultKalashYatraData.hero.primaryBtnText },
      primaryBtnLink: { type: String, default: defaultKalashYatraData.hero.primaryBtnLink },
      secondaryBtnText: { type: String, default: defaultKalashYatraData.hero.secondaryBtnText },
      secondaryBtnLink: { type: String, default: defaultKalashYatraData.hero.secondaryBtnLink },
      stats: [
        {
          number: { type: String, default: "" },
          label: { type: String, default: "" },
          sub: { type: String, default: "" },
        },
      ],
      featuredVideo: {
        title: { type: String, default: defaultKalashYatraData.hero.featuredVideo.title },
        duration: { type: String, default: defaultKalashYatraData.hero.featuredVideo.duration },
        videoUrl: { type: String, default: defaultKalashYatraData.hero.featuredVideo.videoUrl },
        posterImage: { type: String, default: defaultKalashYatraData.hero.featuredVideo.posterImage },
        badge: { type: String, default: defaultKalashYatraData.hero.featuredVideo.badge },
      },
    },

    milestonesSection: {
      kicker: { type: String, default: defaultKalashYatraData.milestonesSection.kicker },
      title: { type: String, default: defaultKalashYatraData.milestonesSection.title },
      titleHighlight: { type: String, default: defaultKalashYatraData.milestonesSection.titleHighlight },
      subtitle: { type: String, default: defaultKalashYatraData.milestonesSection.subtitle },
      items: [
        {
          stateKey: { type: String, default: "bihar" },
          stateName: { type: String, default: "" },
          district: { type: String, default: "" },
          title: { type: String, default: "" },
          image: { type: String, default: "" },
          description: { type: String, default: "" },
          tag: { type: String, default: "" },
          videoUrl: { type: String, default: "" },
          order: { type: Number, default: 0 },
        },
      ],
    },

    videos: [
      {
        title: { type: String, required: true },
        videoUrl: { type: String, required: true },
        videoPublicId: { type: String, default: "" },
        thumbnail: { type: String, default: "" },
        thumbnailPublicId: { type: String, default: "" },
        personOrPlace: { type: String, default: "" },
        peopleCount: { type: String, default: "5,000+" },
        category: {
          type: String,
          enum: ["all", "yatra", "program", "speech", "sankalp"],
          default: "yatra",
        },
        state: { type: String, default: "bihar" },
        district: { type: String, default: "" },
        duration: { type: String, default: "10:00 Min" },
        viewsCount: { type: String, default: "10K" },
        date: { type: String, default: "" },
        description: { type: String, default: "" },
        tag: { type: String, default: "संकल्प यात्रा" },
        order: { type: Number, default: 0 },
        isHighlighted: { type: Boolean, default: false },
      },
    ],

    pillarsSection: {
      kicker: { type: String, default: defaultKalashYatraData.pillarsSection.kicker },
      title: { type: String, default: defaultKalashYatraData.pillarsSection.title },
      titleAccent: { type: String, default: defaultKalashYatraData.pillarsSection.titleAccent },
      subtitle: { type: String, default: defaultKalashYatraData.pillarsSection.subtitle },
      storyCollage: {
        primaryCard: {
          image: { type: String, default: "" },
          badge: { type: String, default: "" },
          title: { type: String, default: "" },
          desc: { type: String, default: "" },
          videoUrl: { type: String, default: "" },
        },
        subCard1: {
          image: { type: String, default: "" },
          tag: { type: String, default: "" },
          title: { type: String, default: "" },
          desc: { type: String, default: "" },
          videoUrl: { type: String, default: "" },
        },
        subCard2: {
          image: { type: String, default: "" },
          tag: { type: String, default: "" },
          title: { type: String, default: "" },
          desc: { type: String, default: "" },
          videoUrl: { type: String, default: "" },
        },
      },
      pillars: [
        {
          number: { type: String, default: "" },
          iconKey: { type: String, default: "water" },
          title: { type: String, default: "" },
          description: { type: String, default: "" },
          order: { type: Number, default: 0 },
        },
      ],
    },

    democraticPledge: {
      enabled: { type: Boolean, default: true },
      badge: { type: String, default: "🇮🇳 ऐतिहासिक लोकतांत्रिक महा-संकल्प" },
      title: { type: String, default: "लोकतांत्रिक संकल्प पत्र" },
      subtitle: { type: String, default: "स्वतंत्र विचार, स्वाभिमान एवं जनमत का संवैधानिक अधिकार" },
      pledgeText: {
        type: String,
        default:
          "आज हम लोकतांत्रिक संकल्प लेते हैं कि आगामी चुनाव में भाजपा के पक्ष में मतदान नहीं करेंगे तथा अपने विवेक और विचार के आधार पर अपने मताधिकार का प्रयोग करेंगे।",
      },
      signOff: { type: String, default: "— समस्त समाज, युवा एवं मातृशक्ति का सामूहिक संकल्प" },
      keyPoints: [{ type: String }],
      videoUrl: { type: String, default: "" },
    },
  },
  { timestamps: true }
);

// Static helper to get existing doc or seed if empty
kalashYatraSchema.statics.getOrSeed = async function () {
  let doc = await this.findOne();
  if (!doc) {
    doc = await this.create(defaultKalashYatraData);
  }
  return doc;
};

kalashYatraSchema.statics.defaultData = defaultKalashYatraData;

module.exports = mongoose.model("KalashYatra", kalashYatraSchema);
